export const FETCH_BLOG_POST_REQUEST_LOADING = "FETCH_BLOG_POST_REQUEST_LOADING"
export const FETCH_BLOG_POST_REQUEST_SUCCESS = "FETCH_BLOG_POST_REQUEST_SUCCESS"
export const FETCH_BLOG_POST_REQUEST_ERROR = "FETCH_BLOG_POST_REQUEST_ERROR"


export const FETCH_SINGLE_BLOG_REQUEST_LOADING = "FETCH_SINGLE_BLOG_REQUEST_LOADING"
export const FETCH_SINGLE_BLOG_REQUEST_SUCCESS = "FETCH_SINGLE_BLOG_REQUEST_SUCCESS"
export const FETCH_SINGLE_BLOG_REQUEST_ERROR = "FETCH_SINGLE_BLOG_REQUEST_ERROR"


export const CREATE_BLOG_POST_REQUEST_LOADING = "CREATE_BLOG_POST_REQUEST_LOADING"
export const CREATE_BLOG_POST_REQUEST_SUCCESS = "CREATE_BLOG_POST_REQUEST_SUCCESS"
export const CREATE_BLOG_POST_REQUEST_ERROR = "CREATE_BLOG_POST_REQUEST_ERROR"


export const UPDATE_BLOG_POST_REQUEST_LOADING = "UPDATE_BLOG_POST_REQUEST_LOADING"
export const UPDATE_BLOG_POST_REQUEST_SUCCESS = "UPDATE_BLOG_POST_REQUEST_SUCCESS"
export const UPDATE_BLOG_POST_REQUEST_ERROR = "UPDATE_BLOG_POST_REQUEST_ERROR"
